"""Write a dataset inspection report. Does not train models."""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

from src.config import PROJECT_ROOT
from src.data.loader import load_dataset
from src.data.schema import (
    IDENTITY_BATCH_ID,
    IDENTITY_TIMESTAMP,
    LoadedDataset,
    live_feature_columns,
    reference_columns,
)

DEFAULT_REPORT_PATH = PROJECT_ROOT / "reports" / "indpensim_ingestion_report.md"


def _rel(path: Path) -> Path:
    path = Path(path)
    try:
        return path.resolve().relative_to(PROJECT_ROOT)
    except ValueError:
        return path


def _time_resolution_hours(frame: pd.DataFrame) -> dict[str, float | None]:
    if frame.empty:
        return {"median_dt_h": None, "min_dt_h": None, "max_dt_h": None}
    dts: list[float] = []
    for _, grp in frame.groupby(IDENTITY_BATCH_ID, sort=False):
        t = pd.to_numeric(grp[IDENTITY_TIMESTAMP], errors="coerce").to_numpy()
        d = np.diff(t)
        dts.extend(float(x) for x in d if np.isfinite(x) and x > 0)
    if not dts:
        return {"median_dt_h": None, "min_dt_h": None, "max_dt_h": None}
    arr = np.asarray(dts, dtype=float)
    return {
        "median_dt_h": float(np.median(arr)),
        "min_dt_h": float(np.min(arr)),
        "max_dt_h": float(np.max(arr)),
    }


def inspect_loaded(loaded: LoadedDataset) -> dict:
    frame = loaded.frame
    rows_per_batch = (
        frame.groupby(IDENTITY_BATCH_ID, sort=False).size().to_dict()
        if not frame.empty and IDENTITY_BATCH_ID in frame.columns
        else {}
    )
    missing = (
        frame.isna().sum().sort_values(ascending=False)
        if not frame.empty
        else pd.Series(dtype=int)
    )
    missing = missing[missing > 0]
    original_cols = [
        c
        for c in frame.columns
        if c
        not in {
            IDENTITY_BATCH_ID,
            IDENTITY_TIMESTAMP,
            "relative_time_h",
            "source_dataset",
            "source_path",
        }
    ]
    res = _time_resolution_hours(frame)
    return {
        "dataset_found": loaded.dataset_found,
        "source_kind": loaded.source_kind,
        "source_paths": [str(_rel(p)) for p in loaded.source_paths],
        "n_batches": loaded.n_batches,
        "n_rows": int(len(frame)),
        "rows_per_batch": {str(k): int(v) for k, v in rows_per_batch.items()},
        "available_columns": original_cols,
        "identity_columns": [
            "batch_id",
            "timestamp_h",
            "relative_time_h",
            "source_dataset",
            "source_path",
        ],
        "column_map": dict(loaded.column_map),
        "live_feature_columns": live_feature_columns(loaded.column_map),
        "reference_variables": reference_columns(loaded.column_map),
        "missing_value_counts": {str(k): int(v) for k, v in missing.items()},
        "time_resolution_h": res,
        "notes": list(loaded.notes),
    }


def format_report(info: dict) -> str:
    found = info["dataset_found"]
    status = (
        "FOUND (simulator reference dump or extract — not physical industrial data)"
        if found
        else "NOT FOUND in data/raw/ — report uses the labeled synthetic fixture only"
    )
    lines = [
        "# IndPenSim ingestion inspection",
        "",
        "Generated by `python -m src.data.inspect`. No model training.",
        "",
        "## Dataset location",
        "",
        f"- Status: **{status}**",
        f"- Internal source_kind: `{info['source_kind']}`",
        f"- Paths: {info['source_paths'] or '(none)'}",
        "",
        "Place the official Goldrick/Mendeley 100-batch files in `data/raw/`, e.g.",
        "`100_Batches_IndPenSim_V3.csv` from https://data.mendeley.com/datasets/pdnjz7zz5x/1",
        "(CC BY 4.0). IndPenSim is a **simulator**, not plant ground truth.",
        "Raw files under `data/raw/` are gitignored (workspace-only unless you add them).",
        "",
        "## Counts",
        "",
        f"- Number of batches: **{info['n_batches']}**",
        f"- Total rows: **{info['n_rows']}**",
        "",
        "### Rows per batch",
        "",
    ]
    if info["rows_per_batch"]:
        lines.append("| batch_id | n_rows |")
        lines.append("| --- | ---: |")
        for bid, n in info["rows_per_batch"].items():
            lines.append(f"| {bid} | {n} |")
    else:
        lines.append("_No batches loaded._")
    lines += [
        "",
        "## Time resolution",
        "",
        f"- Median Δt (h): {info['time_resolution_h']['median_dt_h']}",
        f"- Min Δt (h): {info['time_resolution_h']['min_dt_h']}",
        f"- Max Δt (h): {info['time_resolution_h']['max_dt_h']}",
        "",
        "Published IndPenSim online sampling is typically **0.2 h (12 min)**.",
        "Offline assays (biomass, penicillin, viscosity, PAA, NH3) are typically every **4 h**.",
        "",
        "## Available columns (source, excluding added identity fields)",
        "",
    ]
    if info["available_columns"]:
        for c in info["available_columns"]:
            lines.append(f"- `{c}`")
    else:
        lines.append("_None._")
    lines += ["", "## Column mapping (documented roles → source header)", ""]
    if info["column_map"]:
        lines.append("| role | source column |")
        lines.append("| --- | --- |")
        for role, col in info["column_map"].items():
            lines.append(f"| `{role}` | `{col}` |")
    else:
        lines.append("_No documented roles matched._")
    lines += ["", "## Live feature subset (no reference biomass)", ""]
    live = info["live_feature_columns"]
    if live:
        for role, col in live.items():
            lines.append(f"- `{role}` ← `{col}`")
    else:
        lines.append("_None identified._")
    lines += ["", "## Reference / state variables", ""]
    refs = info["reference_variables"]
    if refs:
        for role, col in refs.items():
            extra = " (hidden from live inference features)" if role == "biomass_reference" else ""
            lines.append(f"- `{role}` ← `{col}`{extra}")
    else:
        lines.append("_No documented reference state columns found._")
    if "jacket_temperature" not in info["column_map"]:
        lines += [
            "",
            "Jacket temperature is **not** mapped: it is not a documented IndPenSim "
            "column in the published process table (vessel `Temperature(T:K)` is).",
        ]
    lines += ["", "## Missing values (count of NA per column)", ""]
    miss = info["missing_value_counts"]
    if miss:
        lines.append("| column | n_missing |")
        lines.append("| --- | ---: |")
        for col, n in miss.items():
            lines.append(f"| `{col}` | {n} |")
    else:
        lines.append("_No missing values in the loaded table._")
    lines += ["", "## Loader notes", ""]
    for note in info["notes"]:
        lines.append(f"- {note}")
    lines += ["", "End of report.", ""]
    return "\n".join(lines)


def write_inspection_report(
    path: Path | None = None,
    *,
    fallback_fixture: bool = True,
) -> Path:
    dest = Path(path) if path is not None else DEFAULT_REPORT_PATH
    dest.parent.mkdir(parents=True, exist_ok=True)
    loaded = load_dataset(fallback_fixture=fallback_fixture)
    text = format_report(inspect_loaded(loaded))
    dest.write_text(text, encoding="utf-8")
    return dest


def main() -> None:
    dest = write_inspection_report()
    print(f"Wrote {dest}")


if __name__ == "__main__":
    main()
